# Generated by Django 6.0.4 on 2026-05-02 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('hair', 'Hair'), ('nails', 'Nails'), ('face', 'Face'), ('body', 'Body')], default='hair', max_length=20),
        ),
    ]
