# Generated by Django 6.0.1 on 2026-05-10 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_appointment_client_alter_appointment_employee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='appointmentservice',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
