# Generated by Django 6.0.4 on 2026-05-11 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_appointment_total_price_appointmentservice_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('hair_styling', 'Hair'), ('nails_care', 'Nails'), ('facial_care', 'Face'), ('body', 'Body')], default='hair', max_length=20),
        ),
    ]
