# Generated by Django 6.0.4 on 2026-05-11 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_alter_service_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('hair_styling', 'Hair styling'), ('nails_care', 'Nails care'), ('facial_care', 'Face care'), ('body', 'Body')], default='hair', max_length=20),
        ),
    ]
