# Generated by Django 6.0.4 on 2026-05-11 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_alter_service_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('hair styling', 'Hair styling'), ('nails care', 'Nails care'), ('facial care', 'Face care'), ('body', 'Body')], default='hair', max_length=20),
        ),
    ]
