# Generated by Django 6.0.4 on 2026-05-11 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_alter_service_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('hair', 'Hair'), ('nails', 'Nails'), ('facial', 'Face'), ('body', 'Body')], default='hair', max_length=20),
        ),
    ]
