# Generated by Django 6.0.4 on 2026-05-02 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_service_category'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='speciality',
        ),
        migrations.AddField(
            model_name='employee',
            name='services',
            field=models.ManyToManyField(to='booking.service'),
        ),
    ]
