# Generated by Django 6.0.4 on 2026-05-02 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_employee_speciality_employee_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('client', 'Client'), ('employee', 'Employee')], default='client', max_length=20),
        ),
    ]
